"""
Swing Engine — pivot detection using LuxAlgo leg() method.

Leg function:
  leg(size) → BEARISH_LEG (0) if high[size] > highest(high, size) [pivot high]
            → BULLISH_LEG (1) if low[size]  < lowest(low,  size) [pivot low]

At bar index i (where i >= size):
  - high[i - size] > max(high[i-size+1 : i+1])  → BEARISH_LEG (swing high confirmed)
  - low[i - size]  < min(low[i-size+1 : i+1])   → BULLISH_LEG (swing low confirmed)

Leg change → pivot confirmed at bar i - size.
"""

from typing import Optional
from .models import PivotPoint, Bar, Snapshot, Event
from .config import EngineConfig, BULLISH, BEARISH, BULLISH_LEG, BEARISH_LEG
from .no_lookahead_guard import NoLookaheadGuard


class SwingEngine:
    """Detects swing highs, swing lows, internal swing highs/lows."""

    def __init__(self, config: EngineConfig, guard: NoLookaheadGuard):
        self.cfg = config
        self.guard = guard
        self.swing_length = config.swing_length       # 50 (LuxAlgo default)
        self.internal_length = config.internal_length  # 5  (LuxAlgo default)

        # Stateful leg trackers
        self.swing_leg = BEARISH_LEG    # 0
        self.internal_leg = BEARISH_LEG

        # Pivot points (LuxAlgo-style pivot UDT)
        self.swing_high = PivotPoint("swing_high", 0.0, 0, 0)
        self.swing_low = PivotPoint("swing_low", 0.0, 0, 0)
        self.internal_high = PivotPoint("internal_high", 0.0, 0, 0)
        self.internal_low = PivotPoint("internal_low", 0.0, 0, 0)

        # Trailing extremes (for premium/discount)
        self.trailing_top = 0.0
        self.trailing_bottom = float("inf")
        self.trailing_top_bar = 0
        self.trailing_bottom_bar = 0
        self.trailing_top_time = 0
        self.trailing_bottom_time = 0

        # History buffers (mirror LuxAlgo arrays)
        self.highs: list[float] = []
        self.lows: list[float] = []
        self.times: list[int] = []

        # Equal highs/lows
        self.equal_highs: list = []
        self.equal_lows: list = []

        # ATR tracker
        self.atr_value: float = 0.0
        self.atr_period = config.order_block.atr_period
        self.tr_history: list[float] = []

    def on_bar(self, bar: Bar, bar_index: int, snapshot: Snapshot) -> list[Event]:
        """Process one bar. Returns events generated by swing detection."""
        events: list[Event] = []

        # Store raw data (LuxAlgo arrays)
        self.highs.append(bar.high)
        self.lows.append(bar.low)
        self.times.append(bar.timestamp)

        # Update trailing extremes
        if bar.high > self.trailing_top or self.trailing_top == 0:
            self.trailing_top = bar.high
            self.trailing_top_bar = bar_index
            self.trailing_top_time = bar.timestamp
        if bar.low < self.trailing_bottom:
            self.trailing_bottom = bar.low
            self.trailing_bottom_bar = bar_index
            self.trailing_bottom_time = bar.timestamp

        # Update ATR
        tr = max(bar.high - bar.low,
                 abs(bar.high - (self.highs[-2] if len(self.highs) > 1 else bar.close)),
                 abs(bar.low - (self.lows[-2] if len(self.lows) > 1 else bar.close)))
        self.tr_history.append(tr)
        if len(self.tr_history) > self.atr_period:
            self.tr_history.pop(0)
        self.atr_value = sum(self.tr_history) / max(len(self.tr_history), 1)

        # Check swing pivots
        if bar_index >= self.swing_length:
            s_events = self._check_pivot(self.swing_length, "swing", bar_index)
            events.extend(s_events)

        # Check internal pivots
        if bar_index >= self.internal_length:
            i_events = self._check_pivot(self.internal_length, "internal", bar_index)
            events.extend(i_events)

        # Equal highs/lows check (LuxAlgo: during pivot detection)
        if self.cfg.show_equal_highs_lows and bar_index >= self.cfg.liquidity.bars_confirmation:
            eq_events = self._check_equal_levels(bar_index)
            events.extend(eq_events)

        # Update snapshot
        snapshot.last_swing_high = self.swing_high.price
        snapshot.last_swing_low = self.swing_low.price
        snapshot.last_internal_high = self.internal_high.price
        snapshot.last_internal_low = self.internal_low.price
        snapshot.last_swing_leg = self.swing_leg
        snapshot.last_internal_leg = self.internal_leg

        return events

    def _check_pivot(self, size: int, level: str, bar_index: int) -> list[Event]:
        """LuxAlgo leg()-based pivot detection at bar_index.
        Check bar at index (bar_index - size) for pivot status.

        Returns:
            events generated by this detection
        """
        events: list[Event] = []
        pivot_idx = bar_index - size   # the bar being evaluated

        # LuxAlgo leg() logic
        new_leg_high = self.highs[pivot_idx] > max(self.highs[pivot_idx + 1: bar_index + 1])
        new_leg_low = self.lows[pivot_idx] < min(self.lows[pivot_idx + 1: bar_index + 1])

        prev_leg = self.swing_leg if level == "swing" else self.internal_leg
        current_leg = prev_leg

        if new_leg_high:
            current_leg = BEARISH_LEG  # 0 — swing high
        elif new_leg_low:
            current_leg = BULLISH_LEG  # 1 — swing low

        leg_changed = current_leg != prev_leg
        started_bullish = leg_changed and current_leg == BULLISH_LEG   # new swing LOW
        started_bearish = leg_changed and current_leg == BEARISH_LEG   # new swing HIGH

        # Guard: check pivot confirmation timing
        self.guard.check_pivot_timing(
            pivot_idx, bar_index, size,
            f"{level}_pivot at bar {pivot_idx}"
        )

        # Get the right pivot point references
        is_swing = (level == "swing")
        pivot_high = self.swing_high if is_swing else self.internal_high
        pivot_low = self.swing_low if is_swing else self.internal_low

        if started_bullish:
            # New swing LOW at pivot_idx
            pivot_low.last_level = pivot_low.price
            pivot_low.price = self.lows[pivot_idx]
            pivot_low.crossed = False
            pivot_low.bar_index = pivot_idx
            pivot_low.timestamp = self.times[pivot_idx]
            pivot_low.leg = BULLISH_LEG

            if is_swing:
                self.trailing_bottom = pivot_low.price
                self.trailing_bottom_bar = pivot_idx
                self.trailing_bottom_time = self.times[pivot_idx]

            events.append(Event(
                timestamp=self.times[pivot_idx],
                bar_index=pivot_idx,
                symbol="",
                timeframe="",
                event_type="SWING_LOW" if is_swing else "INTERNAL_SWING_LOW",
                direction=BULLISH,
                price=self.lows[pivot_idx],
                confirmed=True,
            ))

        elif started_bearish:
            # New swing HIGH at pivot_idx
            pivot_high.last_level = pivot_high.price
            pivot_high.price = self.highs[pivot_idx]
            pivot_high.crossed = False
            pivot_high.bar_index = pivot_idx
            pivot_high.timestamp = self.times[pivot_idx]
            pivot_high.leg = BEARISH_LEG

            if is_swing:
                self.trailing_top = pivot_high.price
                self.trailing_top_bar = pivot_idx
                self.trailing_top_time = self.times[pivot_idx]

            events.append(Event(
                timestamp=self.times[pivot_idx],
                bar_index=pivot_idx,
                symbol="",
                timeframe="",
                event_type="SWING_HIGH" if is_swing else "INTERNAL_SWING_HIGH",
                direction=BEARISH,
                price=self.highs[pivot_idx],
                confirmed=True,
            ))

        # Update leg
        if is_swing:
            self.swing_leg = current_leg
        else:
            self.internal_leg = current_leg

        return events

    def _check_equal_levels(self, bar_index: int) -> list[Event]:
        """LuxAlgo equal high/low detection."""
        events: list[Event] = []
        size = self.cfg.liquidity.bars_confirmation
        threshold = self.cfg.liquidity.threshold * self.atr_value

        if bar_index >= size:
            pivot_idx = bar_index - size

            # Check equal low
            if self.swing_low.price > 0 and abs(self.swing_low.price - self.lows[pivot_idx]) < threshold:
                is_new = True
                for eq in self.equal_lows:
                    if abs(eq.price - self.lows[pivot_idx]) < threshold:
                        is_new = False
                        break
                if is_new:
                    self.equal_lows.append(PivotPoint("equal_low", self.lows[pivot_idx], pivot_idx, self.times[pivot_idx]))
                    events.append(Event(
                        timestamp=self.times[pivot_idx],
                        bar_index=pivot_idx,
                        symbol="", timeframe="",
                        event_type="EQUAL_LOW",
                        direction=BULLISH,
                        price=self.lows[pivot_idx],
                        confirmed=True,
                    ))

            # Check equal high
            if self.swing_high.price > 0 and abs(self.swing_high.price - self.highs[pivot_idx]) < threshold:
                is_new = True
                for eq in self.equal_highs:
                    if abs(eq.price - self.highs[pivot_idx]) < threshold:
                        is_new = False
                        break
                if is_new:
                    self.equal_highs.append(PivotPoint("equal_high", self.highs[pivot_idx], pivot_idx, self.times[pivot_idx]))
                    events.append(Event(
                        timestamp=self.times[pivot_idx],
                        bar_index=pivot_idx,
                        symbol="", timeframe="",
                        event_type="EQUAL_HIGH",
                        direction=BEARISH,
                        price=self.highs[pivot_idx],
                        confirmed=True,
                    ))

        return events
